extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- NetSpeed: NetSpeed.md
site_name: NetSpeed's Documentation
site_url: https://docs.prismbot.icu/NetSpeed/
theme:
  name: dracula
use_directory_urls: false
