extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Banner: Banner.md
site_name: Banner's Documentation
site_url: https://docs.prismbot.icu/Banner/
theme:
  name: dracula
use_directory_urls: false
