extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- MemberHistory: MemberHistory.md
site_name: MemberHistory's Documentation
site_url: https://docs.prismbot.icu/MemberHistory/
theme:
  name: dracula
use_directory_urls: false
