extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- BanAppeal: BanAppeal.md
site_name: BanAppeal's Documentation
site_url: https://docs.prismbot.icu/BanAppeal/
theme:
  name: dracula
use_directory_urls: false
