extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Banana: Banana.md
site_name: Banana's Documentation
site_url: https://docs.prismbot.icu/Banana/
theme:
  name: dracula
use_directory_urls: false
