extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- SentryTestCog: SentryTestCog.md
site_name: SentryTestCog's Documentation
site_url: https://docs.prismbot.icu/SentryTestCog/
theme:
  name: dracula
use_directory_urls: false
