extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Audio: Audio.md
site_name: Audio's Documentation
site_url: https://docs.prismbot.icu/Audio/
theme:
  name: dracula
use_directory_urls: false
