extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- DynamicPrefix: DynamicPrefix.md
site_name: DynamicPrefix's Documentation
site_url: https://docs.prismbot.icu/DynamicPrefix/
theme:
  name: dracula
use_directory_urls: false
