extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Admin: Admin.md
site_name: Admin's Documentation
site_url: https://docs.prismbot.icu/Admin/
theme:
  name: dracula
use_directory_urls: false
