extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- FluxImgGen: FluxImgGen.md
site_name: FluxImgGen's Documentation
site_url: https://docs.prismbot.icu/FluxImgGen/
theme:
  name: dracula
use_directory_urls: false
