extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Star_Utils: Star_Utils.md
site_name: Star_Utils's Documentation
site_url: https://docs.prismbot.icu/Star_Utils/
theme:
  name: dracula
use_directory_urls: false
