extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- GitHub: GitHub.md
site_name: GitHub's Documentation
site_url: https://docs.prismbot.icu/GitHub/
theme:
  name: dracula
use_directory_urls: false
