extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- AssistantUtils: AssistantUtils.md
site_name: AssistantUtils's Documentation
site_url: https://docs.prismbot.icu/AssistantUtils/
theme:
  name: dracula
use_directory_urls: false
