extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Gulag: Gulag.md
site_name: Gulag's Documentation
site_url: https://docs.prismbot.icu/Gulag/
theme:
  name: dracula
use_directory_urls: false
