extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Avatar: Avatar.md
site_name: Avatar's Documentation
site_url: https://docs.prismbot.icu/Avatar/
theme:
  name: dracula
use_directory_urls: false
