extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- EmojiTools: EmojiTools.md
site_name: EmojiTools's Documentation
site_url: https://docs.prismbot.icu/EmojiTools/
theme:
  name: dracula
use_directory_urls: false
