extra:
  footer: Created by [Rosie](https://github.com/PBOwner) with <3
nav:
- Home: index.md
- Mod: Mod.md
site_name: Mod's Documentation
site_url: https://docs.prismbot.icu/Mod/
theme:
  name: dracula
use_directory_urls: false
